#!/usr/bin/env bash
#
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

# Default editor: vim
set -o vi
export EDITOR=vim
export VISUAL=vim

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="gazay"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Work path
alias gow='cd ~/code/martians/amplifr-projects/amplifr'
alias gop='cd ~/code/martians/amplifr-projects'
alias god='cd ~/code/dl'

alias prod="~/.get_amplifr_prod.sh"
alias ssh_to="~/.ssh_to_pod.sh"

# Python, Jupyter
alias jp='jupyter notebook'

# PS
alias psa="ps aux"
alias psg="ps aux | grep "
alias psr='ps aux | grep ruby'

# Show human friendly numbers and colors
alias df='df -h'
alias du='du -h -d 2'

# Zippin
alias gz='tar -zcvf'
alias ugz='tar -xzvf'

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

alias ll='ls -alh --color=auto'
alias ls='ls --color=auto'

# Functions
#
# (f)ind by (n)ame
# usage: fn foo
# to find all files containing 'foo' in the name
function fn() { ls **/*$1* }

# Chruby env
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

chruby 2.5.3

# Amplifr setup
export DATABASE_URL=postgresql://postgres@localhost/amplifr_development
export SLAVE_DATABASE_URL=postgresql://postgres@localhost/amplifr_development
export PUMA_PORT=3000
export RAILS_ENV=development
export RACK_ENV=development
export PUMA_MIN_THREADS=2
export PUMA_MAX_THREADS=8
export PUMA_CONCURRENCY=2
export REDIS_URL=redis://localhost

export PATH="$HOME/.yarn/bin:$PATH"
