#!/usr/bin/env bash
#
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

# Default editor: vim
set -o vi
export EDITOR=vim
export VISUAL=vim

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="gazay"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Mapping to nvim
if type nvim > /dev/null 2>&1; then
  alias vim='nvim'
fi

# Work path
alias gow='cd ~/code/martians'

# Python, Jupyter
alias jp='jupyter notebook'

# Show human friendly numbers and colors
alias df='df -h'
alias du='du -h -d 2'

# Zippin
alias gz='tar -zcvf'
alias ugz='tar -xzvf'

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

alias ll='ls -alh --color=auto'
alias ls='ls --color=auto'

alias yaus='yarn cache clean && rm -R node_modules && yarn && yarn start'

# Functions
#
# (f)ind by (n)ame
# usage: fn foo
# to find all files containing 'foo' in the name
function fn() { ls **/*$1* }

# Chruby env
if type chruby > /dev/null 2>&1; then
  source /usr/local/share/chruby/chruby.sh
  source /usr/local/share/chruby/auto.sh

  chruby 2.6.5
fi

# Cuda
export PATH=/usr/local/cuda-10.1/bin${PATH:+:${PATH}}
export CUDADIR=/usr/local/cuda-10.1
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

# Anaconda
export PATH="/home/gazay/anaconda3/bin:$PATH"
export CMAKE_PREFIX_PATH="/home/gazay/anaconda3/"

# Python envs
alias py37='conda activate py37'
alias py27='conda activate py27'
alias pysys='conda deactivate'

py37

# XDG
export XDG_CONFIG_HOME=$HOME/.config
