" Run pathogen
execute pathogen#infect()

" Syntax highlighting
syntax on
" Autodetect filetype
filetype plugin indent on

" Shared clipboard
set clipboard=unnamedplus
" Set line numbers display
set nu

" Split characters set
set enc=utf-8
set fillchars+=vert:\|
set fillchars+=stl:\-
set fillchars+=stlnc:\-

" Theme colors and font
color solarized
set background=light
set gfn=Menlo:h16

autocmd BufWritePre * :%s/\s\+$//e

" Support for github flavored markdown
" via https://github.com/jtratner/vim-flavored-markdown
augroup markdown
    au!
    au BufNewFile,BufRead *.md,*.markdown setlocal filetype=ghmarkdown
augroup END

" DVC
autocmd! BufNewFile,BufRead Dvcfile,*.dvc setfiletype yaml

" Don't write backup files
set nobackup
set nowritebackup

" Search settings
set incsearch
set ignorecase

" Mouse options
set mouse=a
set scrolloff=5

" Indentation settings
set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
set autoindent

" Less timeout for keycode entering
set ttimeoutlen=100

" Nerdtree mapped to cmd-N
let NERDTreeAutoDeleteBuffer=1
map <C-n> :NERDTreeToggle<CR>

" Allow NerdTree to show hidden files
let NERDTreeShowHidden=1

" Run nerdtree on startup
function! StartUp()
  if 0 == argc()
    NERDTree
  end
endfunction

autocmd VimEnter * call StartUp()

" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'neomake/neomake'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" Neomake and syntastic
" Run NeoMake on read and write operations
autocmd! BufReadPost,BufWritePost * Neomake

" Disable inherited syntastic
let g:syntastic_mode_map = {
  \ "mode": "passive",
  \ "active_filetypes": [],
  \ "passive_filetypes": [] }

let g:neomake_serialize = 1
let g:neomake_serialize_abort_on_error = 1
